### ISSUE TITLE
getting connection failed error

### ISSUE THREAD

**Issue by atik7** [asimsedhain/solace-rs#2]
Thanks for nice crates, waiting for this long time.

any idea why getting connection failed error, connection seems ok from solace go library

Context created
on_event handler got: Session connection attempt failed
thread 'main' panicked at 'Could not create session: ConnectionFailure', src/main.rs:55:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by asimsedhain** [comment]
Could you post the snippet you are using to connect with the broker? I will try to see if I can recreate it on my end.

**Comment by atik7** [comment]
I was using the subscriber example code, just modified credentials :-)

**Comment by asimsedhain** [comment]
Hey @atik7,
I tried it using the docker-compose provided in the repo and was not able to recreate it.
Tested it by creating additional users and vpns as well.
Could you provide the traceback? Maybe that will show something. Sadly, the library currently does not expose subcodes (will add support in the future).

**Comment by atik7** [comment]
Context created
on_event handler got: Session connection attempt failed
thread 'main' panicked at 'Could not create session: ConnectionFailure', src/main.rs:48:10
stack backtrace:
   0:     0x56023d71e5da - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56023d71e5da - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56023d71e5da - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x56023d71e5da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56023d73898f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x56023d71c375 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x56023d71e3a5 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x56023d71e3a5 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x56023d71f92e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x56023d71f6d5 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x56023d71fe8e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x56023d71fd89 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x56023d71ea46 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x56023d71fae2 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x56023d6419e3 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x56023d641dd3 - core::result::unwrap_failed::h8090202169109f9c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  16:     0x56023d642c6f - solace_new::main::hc286e48218cd866e
  17:     0x56023d642813 - std::sys_common::backtrace::__rust_begin_short_backtrace::h80042aa126180b96
  18:     0x56023d6427e9 - std::rt::lang_start::{{closure}}::hf12d724f1ff46e7a
  19:     0x56023d719f0e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  20:     0x56023d719f0e - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  21:     0x56023d719f0e - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  22:     0x56023d719f0e - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  23:     0x56023d719f0e - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  24:     0x56023d719f0e - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  25:     0x56023d719f0e - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  26:     0x56023d719f0e - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  27:     0x56023d719f0e - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  28:     0x56023d642d85 - main
  29:     0x7f23361c2d85 - __libc_start_main
  30:     0x56023d641f1e - _start
  31:                0x0 - <unknown>

**Comment by asimsedhain** [comment]
Yeah, still not sure what might be causing the connection to fail.

Could you post more info on the device you are running it on (arch, OS, rust version)? I will try to create it if I have the device available.

Also could you try connecting to solace broker running using the [docker-compose](https://github.com/asimsedhain/solace-rs/blob/main/docker-compose.yaml) in the repo (if you have not done so already)? Just trying to eliminate possible causes.

**Comment by atik7** [comment]
not sure how, but with new release this issue solved,
