### ISSUE TITLE
release mode doing coredump

### ISSUE THREAD

**Issue by atik7** [asimsedhain/solace-rs#6]
Hi, 

when i ran with cargo run, its worked fine, but release mode doing coredump, any idea?

(gdb) bt
0  0x00007f446bcb4e35 in __strlen_avx2 () from /lib64/libc.so.6
1  0x00007f446bc5184d in vfprintf () from /lib64/libc.so.6
2  0x00007f446bc77f74 in vsnprintf () from /lib64/libc.so.6
3  0x0000560ae898af33 in _solClient_logAndStoreSubCodeAndErrorString_impl (
    subCode=subCode@entry=SOLCLIENT_SUBCODE_PARAM_NULL_PTR, level=level@entry=SOLCLIENT_LOG_WARNING, 
    filename_p=filename_p@entry=0x560ae8a79e60 "//opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientSession.c", lineNum=lineNum@entry=1516, 
    format_p=format_p@entry=0x560ae8a7a8b0 "Session '%s' configuration property: '%s' has null data value pointer")
    at /opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientLog.c:456
4  0x0000560ae89a08ed in _solClient_handleSessionProps (session_p=session_p@entry=0x560ae9eef9a0, 
    props=props@entry=0x7ffe584d4340, hostProperty_p=hostProperty_p@entry=0x7ffe584d4020)
    at /opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientSession.c:1512
5  0x0000560ae89a5802 in _solClient_internalSessionCreate (props=<optimized out>, context_p=0x560ae9eeeea0, 
    createdSession_p=<optimized out>, funcInfo_p=<optimized out>, parent_p=0x0, caller_p=<optimized out>, 
    configSslGssKrb=1 '\001', clientCert_p=0x0, chainCerts_a=0x0, numChainCerts=0, trustedCerts_a=0x0, numTrustedCerts=0)
    at /opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientSession.c:3729
6  0x0000560ae89a604a in __solClient_session_create (props=0x7ffe584d4340, opaqueContext_p=<optimized out>, 
    opaqueSession_p=0x7ffe584d4338, funcInfo_p=0x7ffe584d42e0, funcInfoSize=48, clientCert_p=clientCert_p@entry=0x0, 
    chainCerts_a=chainCerts_a@entry=0x0, numChainCerts=numChainCerts@entry=0, trustedCerts_a=trustedCerts_a@entry=0x0, 
    numTrustedCerts=numTrustedCerts@entry=0)
    at /opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientSession.c:4283
7  0x0000560ae89a64df in solClient_session_create (props=<optimized out>, opaqueContext_p=<optimized out>, 
    opaqueSession_p=<optimized out>, funcInfo_p=<optimized out>, funcInfoSize=<optimized out>)
    at /opt/cvsdirs/loadbuild/jenkins/slave/workspace/ccsmp-build/impl/solClientSession.c:4427
8  0x0000560ae895571c in solace_rs::context::Context::session ()
9  0x0000560ae8956cc2 in solace_new::main ()
10 0x0000560ae89538d3 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
11 0x0000560ae8953a59 in std::rt::lang_start::{{closure}} ()
12 0x0000560ae8a33351 in core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once ()
    at library/core/src/ops/function.rs:284
13 std::panicking::try::do_call () at library/std/src/panicking.rs:552
14 std::panicking::try () at library/std/src/panicking.rs:516
15 std::panic::catch_unwind () at library/std/src/panic.rs:142
16 std::rt::lang_start_internal::{{closure}} () at library/std/src/rt.rs:148
17 std::panicking::try::do_call () at library/std/src/panicking.rs:552
18 std::panicking::try () at library/std/src/panicking.rs:516
19 std::panic::catch_unwind () at library/std/src/panic.rs:142
20 std::rt::lang_start_internal () at library/std/src/rt.rs:148
21 0x0000560ae8957235 in main () at library/std/src/sys/unix/futex.rs:104

**Comment by atik7** [comment]
Context created
SDK WARNING Mon Feb 19 04:13:41.606 2024 solClientSession.c:1516              (7fde01548780) Session '(c0,s1)' configuration property: '' has null data value pointer
Could not create session: InitializationFailure

**Comment by asimsedhain** [comment]
I can re-create it on my end. Still investigating on the root issue.

**Comment by asimsedhain** [comment]
Implemented a fix in version v0.3.3. Could you give it a shot?

**Comment by atik7** [comment]
nice, working now, thanks a lot,
